name: build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - ocaml-variants.4.14.0+options,ocaml-option-flambda

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup OCaml Env
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - name: Install dependencies
        run: opam install . --deps-only
      - name: Build
        run: opam exec -- dune build
      - run: mv _build/default/src/Main.exe lab-tools
      - run: chmod 755 lab-tools
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: lab-tools
      - uses: actions/upload-artifact@v3
        with:
          name: lab-tools-${{ matrix.os }}
          path: lab-tools
