name: build

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on:
      - ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup OCaml Env
        uses: ocaml/setup-ocaml@v1.1.11
        with:
          ocaml-version: 4.14.0 --package=ocaml-variants.4.14.0+options,ocaml-option-flambda
      - name: Setup Rust Env
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: opam install . --deps-only
      - name: Build
        run: opam exec -- dune build
